extends Node
class_name PhysicsLayers

const PLAYER: int = 1 << 0
const ENEMY: int = 1 << 1
const PROJECTILE_PLAYER: int = 1 << 2
const PROJECTILE_ENEMY: int = 1 << 3
const HITBOX: int = 1 << 4
const HURTBOX: int = 1 << 5
const PICKUP: int = 1 << 6
const ENVIRONMENT_AND_TRIGGER: int = 1 << 7

const MASK_PLAYER_BODY: int = ENEMY | PROJECTILE_ENEMY | PICKUP | ENVIRONMENT_AND_TRIGGER
const MASK_ENEMY_BODY: int = PLAYER | PROJECTILE_PLAYER | HITBOX | ENVIRONMENT_AND_TRIGGER
const MASK_PROJECTILE_PLAYER: int = ENEMY | HURTBOX | ENVIRONMENT_AND_TRIGGER
const MASK_PROJECTILE_ENEMY: int = PLAYER | HURTBOX | ENVIRONMENT_AND_TRIGGER
const MASK_HITBOX_PLAYER: int = ENEMY | HURTBOX
const MASK_HURTBOX_PLAYER: int = PROJECTILE_ENEMY | ENVIRONMENT_AND_TRIGGER
const MASK_HURTBOX_ENEMY: int = PROJECTILE_PLAYER | HITBOX
const MASK_PICKUP: int = PLAYER
const MASK_TRIGGER: int = PLAYER


static func layer_table() -> Dictionary:
	return {
		"PLAYER": PLAYER,
		"ENEMY": ENEMY,
		"PROJECTILE_PLAYER": PROJECTILE_PLAYER,
		"PROJECTILE_ENEMY": PROJECTILE_ENEMY,
		"HITBOX": HITBOX,
		"HURTBOX": HURTBOX,
		"PICKUP": PICKUP,
		"ENVIRONMENT_AND_TRIGGER": ENVIRONMENT_AND_TRIGGER,
	}
